language: csharp

matrix:
  include:
    # - os: osx
    #   osx_image: xcode7.3
    #   dotnet: 1.0.0-preview2-003131
    #   mono: none
    - os: linux
      dist: trusty
      dotnet: 1.0.0-preview2-003131
      mono: none
      sudo: required

notifications:
  email:
    on_success: change
    on_failure: always

script:
  time dotnet restore && dotnet test tests/Anat.Tests -c Release -f netcoreapp1.0
